all:
  children:

    core_nodes:
      hosts:
        bizranker-core:
          role: core_demo_node

    ui_nodes:
      hosts:
        bizranker-web-01:
          role: ui_node

    db_nodes:
      hosts:
        bizranker-db-01:
          role: postgres_node

    worker_nodes:
      hosts:
        bizranker-worker-01:
          role: scraper_worker_node

    command_center_nodes:
      hosts:
        bizranker-command-01:
          ansible_host: 165.1.76.210
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/oracle-bizranker.key
          role: command_center_node

api_nodes:
  hosts:
    bizranker-api-01:
      ansible_host: 163.192.47.197
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/oracle-bizranker.key
      role: api_node

k3s_master_nodes:
  hosts:
    bizranker-k3s-master-01:
      ansible_host: 159.54.164.33
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/oracle-bizranker.key
      role: k3s_master_node
