grafana:
  adminPassword: "2421Mission!"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

prometheusOperator:
  admissionWebhooks:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 100m
        memory: 512Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

prometheus-node-exporter:
  enabled: false

nodeExporter:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false
